package Clases;

public class Book {
    
	   private int id;
	   private String name;

	   public Book() {        
	   }

	   public Book(int i, String n){
		   this.id=i;
		   this.name=n;
	   }
	   //mark id as primary key with autogenerated value
	   //map database column id with id field
	   public int getId() {
	      return id;
	   }
	   public String getName() {
	      return name;
	   }
	   public void setName(String Name) {
		   name = Name;
	   }

	@Override
	public String toString() {
		return "Libro: " +
				"Id=" + id +
				", Nombre='" + name + '\'' +
				'}';
	}
}